### ISSUE TITLE
Support for Redmine 5.x

### ISSUE THREAD

**Issue by andreav** [jbbarth/redmine_base_deface#12]
Hello,
I'm trying to use this plugin with Redmine 5.x but I'm getting this error (using master)

Am I making something wrong? 

Thank you!

```
/usr/local/bundle/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/callbacks.rb:25:in `on_file_autoloaded': expected file /usr/src/redmine/plugins/redmine_base_deface/lib/applicator_patch.rb to define constant ApplicatorPatch, but didn't (Zeitwerk::NameError)
redmine-dufercoenergy-redmine-1  |
      raise Zeitwerk::NameError.new("expected file #{file} to define constant #{cpath}, but didn't", cref.last)
      ^^^^^
     from /usr/local/bundle/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:28:in `require'
     from /usr/local/bundle/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:95:in `const_get'
     from /usr/local/bundle/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:95:in `cget'
     from /usr/local/bundle/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:237:in `block (2 levels) in eager_load'
     from /usr/local/bundle/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:26:in `block in ls'
     from /usr/local/bundle/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:18:in `each_child'
     from /usr/local/bundle/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:18:in `ls'
     from /usr/local/bundle/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:232:in `block in eager_load'
     from /usr/local/bundle/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:217:in `synchronize'
     from /usr/local/bundle/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:217:in `eager_load'
     from /usr/local/bundle/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:317:in `each'
     from /usr/local/bundle/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:317:in `eager_load_all'
     from /usr/local/bundle/gems/railties-6.1.4.7/lib/rails/application/finisher.rb:133:in `block in <module:Finisher>'
     from /usr/local/bundle/gems/railties-6.1.4.7/lib/rails/initializable.rb:32:in `instance_exec'
     from /usr/local/bundle/gems/railties-6.1.4.7/lib/rails/initializable.rb:32:in `run'
     from /usr/local/bundle/gems/railties-6.1.4.7/lib/rails/initializable.rb:61:in `block in run_initializers'
     from /usr/local/lib/ruby/3.1.0/tsort.rb:228:in `block in tsort_each'
     from /usr/local/lib/ruby/3.1.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
     from /usr/local/lib/ruby/3.1.0/tsort.rb:431:in `each_strongly_connected_component_from'
     from /usr/local/lib/ruby/3.1.0/tsort.rb:349:in `block in each_strongly_connected_component'
     from /usr/local/lib/ruby/3.1.0/tsort.rb:347:in `each'
     from /usr/local/lib/ruby/3.1.0/tsort.rb:347:in `call'
     from /usr/local/lib/ruby/3.1.0/tsort.rb:347:in `each_strongly_connected_component'
     from /usr/local/lib/ruby/3.1.0/tsort.rb:226:in `tsort_each'
     from /usr/local/lib/ruby/3.1.0/tsort.rb:205:in `tsort_each'
     from /usr/local/bundle/gems/railties-6.1.4.7/lib/rails/initializable.rb:60:in `run_initializers'
     from /usr/local/bundle/gems/railties-6.1.4.7/lib/rails/application.rb:391:in `initialize!'
     from /usr/src/redmine/config/environment.rb:16:in `<top (required)>'
     from /usr/local/bundle/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
     from /usr/local/bundle/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
     from /usr/local/bundle/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
     from /usr/local/bundle/gems/activesupport-6.1.4.7/lib/active_support/dependencies.rb:332:in `block in require'
     from /usr/local/bundle/gems/activesupport-6.1.4.7/lib/active_support/dependencies.rb:299:in `load_dependency'
     from /usr/local/bundle/gems/activesupport-6.1.4.7/lib/active_support/dependencies.rb:332:in `require'
     from config.ru:3:in `block in <main>'
     from /usr/local/bundle/gems/rack-2.2.3/lib/rack/builder.rb:116:in `eval'
     from /usr/local/bundle/gems/rack-2.2.3/lib/rack/builder.rb:116:in `new_from_string'
     from /usr/local/bundle/gems/rack-2.2.3/lib/rack/builder.rb:105:in `load_file'
     from /usr/local/bundle/gems/rack-2.2.3/lib/rack/builder.rb:66:in `parse_file'
     from /usr/local/bundle/gems/rack-2.2.3/lib/rack/server.rb:349:in `build_app_and_options_from_config'
     from /usr/local/bundle/gems/rack-2.2.3/lib/rack/server.rb:249:in `app'
     from /usr/local/bundle/gems/rack-2.2.3/lib/rack/server.rb:422:in `wrapped_app'
     from /usr/local/bundle/gems/rack-2.2.3/lib/rack/server.rb:312:in `block in start'
     from /usr/local/bundle/gems/rack-2.2.3/lib/rack/server.rb:379:in `handle_profiling'
     from /usr/local/bundle/gems/rack-2.2.3/lib/rack/server.rb:311:in `start'
     from /usr/local/bundle/gems/railties-6.1.4.7/lib/rails/commands/server/server_command.rb:39:in `start'
     from /usr/local/bundle/gems/railties-6.1.4.7/lib/rails/commands/server/server_command.rb:144:in `block in perform'
     from <internal:kernel>:90:in `tap'
     from /usr/local/bundle/gems/railties-6.1.4.7/lib/rails/commands/server/server_command.rb:135:in `perform'
     from /usr/local/bundle/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
     from /usr/local/bundle/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
     from /usr/local/bundle/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
     from /usr/local/bundle/gems/railties-6.1.4.7/lib/rails/command/base.rb:69:in `perform'
     from /usr/local/bundle/gems/railties-6.1.4.7/lib/rails/command.rb:48:in `invoke'
     from /usr/local/bundle/gems/railties-6.1.4.7/lib/rails/commands.rb:18:in `<top (required)>'
     from bin/rails:4:in `require'
     from bin/rails:4:in `<main>'
redmine-dufercoenergy-redmine-1 exited with code 1
```

**Comment by DmytroLitvinov** [comment]
Same issue. Does anybody know how to fix it?

**Comment by whotopia** [comment]
Same issue.  One run getting

`
! Unable to load application: Zeitwerk::NameError: expected file /home/finddx-rm/redmine-5.0.0/plugins/redmine_base_deface/lib/applicator_patch.rb to define constant ApplicatorPatch, but didn't



`

**Comment by ashrafalzyoud** [comment]
```
Bundler could not find compatible versions for gem "deface":
  In Gemfile:
    deface (= 1.6.2)

    redmine_plugin_kit was resolved to 1.0.3, which depends on
      deface (= 1.9.0)

```

**Comment by simonefratini** [comment]
Hello, some news?


with this

Rails version 6.1.7
Ruby version ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-linux-gnu]
RubyGems version 3.3.5
Rack version 2.2.4
Middleware ActionDispatch::HostAuthorization, Rack::ContentLength, Rack::Sendfile, ActionDispatch::Static, ActionDispatch::Executor, ActiveSupport::Cache::Strategy::LocalCache::Middleware, Rack::Runtime, Rack::MethodOverride, ActionDispatch::RequestId, RequestStore::Middleware, ActionDispatch::RemoteIp, Rails::Rack::Logger, ActionDispatch::ShowExceptions, ActionDispatch::DebugExceptions, ActionDispatch::ActionableExceptions, ActionDispatch::Callbacks, ActionDispatch::Cookies, ActionDispatch::Session::CookieStore, ActionDispatch::Flash, ActionDispatch::ContentSecurityPolicy::Middleware, ActionDispatch::PermissionsPolicy::Middleware, Rack::Head, Rack::ConditionalGet, Rack::ETag, Rack::TempfileReaper
Application root /opt/redmine-5.0.3
Environment production
Database adapter mysql2
Database schema version 20220224194639

I got this error 

** Invoke redmine:plugins:migrate (first_time)
** Invoke environment (first_time)
** Execute environment
rake aborted!
LoadError: cannot load such file -- maintenance_mode_hooks
/var/lib/gems/3.0.0/gems/zeitwerk-2.6.6/lib/zeitwerk/kernel.rb:38:in `require'
/var/lib/gems/3.0.0/gems/zeitwerk-2.6.6/lib/zeitwerk/kernel.rb:38:in `require'
/var/lib/gems/3.0.0/gems/activesupport-6.1.7/lib/active_support/dependencies/zeitwerk_integration.rb:51:in `require_dependency'
/opt/redmine-5.0.3/plugins/redmine_maintenance_mode/init.rb:1:in `<top (required)>'
/opt/redmine-5.0.3/lib/redmine/plugin_loader.rb:31:in `load'
/opt/redmine-5.0.3/lib/redmine/plugin_loader.rb:31:in `run_initializer'
/opt/redmine-5.0.3/lib/redmine/plugin_loader.rb:108:in `each'
/opt/redmine-5.0.3/lib/redmine/plugin_loader.rb:108:in `block in load'
/var/lib/gems/3.0.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:427:in `instance_exec'
/var/lib/gems/3.0.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:427:in `block in make_lambda'
/var/lib/gems/3.0.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'
/var/lib/gems/3.0.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:604:in `block (2 levels) in default_terminator'
/var/lib/gems/3.0.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:603:in `catch'
/var/lib/gems/3.0.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:603:in `block in default_terminator'
/var/lib/gems/3.0.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:199:in `block in halting'
/var/lib/gems/3.0.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:512:in `block in invoke_before'
/var/lib/gems/3.0.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:512:in `each'
/var/lib/gems/3.0.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:512:in `invoke_before'
/var/lib/gems/3.0.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:105:in `run_callbacks'
/var/lib/gems/3.0.0/gems/activesupport-6.1.7/lib/active_support/reloader.rb:88:in `prepare!'
/var/lib/gems/3.0.0/gems/railties-6.1.7/lib/rails/application/finisher.rb:124:in `block in <module:Finisher>'
/var/lib/gems/3.0.0/gems/railties-6.1.7/lib/rails/initializable.rb:32:in `instance_exec'
/var/lib/gems/3.0.0/gems/railties-6.1.7/lib/rails/initializable.rb:32:in `run'
/var/lib/gems/3.0.0/gems/railties-6.1.7/lib/rails/initializable.rb:61:in `block in run_initializers'
/usr/lib/ruby/3.0.0/tsort.rb:228:in `block in tsort_each'
/usr/lib/ruby/3.0.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
/usr/lib/ruby/3.0.0/tsort.rb:431:in `each_strongly_connected_component_from'
/usr/lib/ruby/3.0.0/tsort.rb:349:in `block in each_strongly_connected_component'
/usr/lib/ruby/3.0.0/tsort.rb:347:in `each'
/usr/lib/ruby/3.0.0/tsort.rb:347:in `call'
/usr/lib/ruby/3.0.0/tsort.rb:347:in `each_strongly_connected_component'
/usr/lib/ruby/3.0.0/tsort.rb:226:in `tsort_each'
/usr/lib/ruby/3.0.0/tsort.rb:205:in `tsort_each'
/var/lib/gems/3.0.0/gems/railties-6.1.7/lib/rails/initializable.rb:60:in `run_initializers'
/var/lib/gems/3.0.0/gems/railties-6.1.7/lib/rails/application.rb:391:in `initialize!'
/opt/redmine-5.0.3/config/environment.rb:16:in `<top (required)>'
/var/lib/gems/3.0.0/gems/zeitwerk-2.6.6/lib/zeitwerk/kernel.rb:38:in `require'
/var/lib/gems/3.0.0/gems/zeitwerk-2.6.6/lib/zeitwerk/kernel.rb:38:in `require'
/var/lib/gems/3.0.0/gems/activesupport-6.1.7/lib/active_support/dependencies.rb:332:in `block in require'
/var/lib/gems/3.0.0/gems/activesupport-6.1.7/lib/active_support/dependencies.rb:299:in `load_dependency'
/var/lib/gems/3.0.0/gems/activesupport-6.1.7/lib/active_support/dependencies.rb:332:in `require'
/var/lib/gems/3.0.0/gems/railties-6.1.7/lib/rails/application.rb:367:in `require_environment!'
/var/lib/gems/3.0.0/gems/railties-6.1.7/lib/rails/application.rb:533:in `block in run_tasks_blocks'
/usr/share/rubygems-integration/all/gems/rake-13.0.6/lib/rake/task.rb:281:in `block in execute'
/usr/share/rubygems-integration/all/gems/rake-13.0.6/lib/rake/task.rb:281:in `each'
/usr/share/rubygems-integration/all/gems/rake-13.0.6/lib/rake/task.rb:281:in `execute'
/usr/share/rubygems-integration/all/gems/rake-13.0.6/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/usr/share/rubygems-integration/all/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'
/usr/share/rubygems-integration/all/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
/usr/share/rubygems-integration/all/gems/rake-13.0.6/lib/rake/task.rb:243:in `block in invoke_prerequisites'
/usr/share/rubygems-integration/all/gems/rake-13.0.6/lib/rake/task.rb:241:in `each'
/usr/share/rubygems-integration/all/gems/rake-13.0.6/lib/rake/task.rb:241:in `invoke_prerequisites'
/usr/share/rubygems-integration/all/gems/rake-13.0.6/lib/rake/task.rb:218:in `block in invoke_with_call_chain'
/usr/share/rubygems-integration/all/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'
/usr/share/rubygems-integration/all/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
/usr/share/rubygems-integration/all/gems/rake-13.0.6/lib/rake/task.rb:188:in `invoke'
/usr/share/rubygems-integration/all/gems/rake-13.0.6/lib/rake/application.rb:160:in `invoke_task'
/usr/share/rubygems-integration/all/gems/rake-13.0.6/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/usr/share/rubygems-integration/all/gems/rake-13.0.6/lib/rake/application.rb:116:in `each'
/usr/share/rubygems-integration/all/gems/rake-13.0.6/lib/rake/application.rb:116:in `block in top_level'
/usr/share/rubygems-integration/all/gems/rake-13.0.6/lib/rake/application.rb:125:in `run_with_threads'
/usr/share/rubygems-integration/all/gems/rake-13.0.6/lib/rake/application.rb:110:in `top_level'
/usr/share/rubygems-integration/all/gems/rake-13.0.6/lib/rake/application.rb:83:in `block in run'
/usr/share/rubygems-integration/all/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
/usr/share/rubygems-integration/all/gems/rake-13.0.6/lib/rake/application.rb:80:in `run'
/usr/share/rubygems-integration/all/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/usr/bin/rake:25:in `load'
/usr/bin/rake:25:in `<main>'
Tasks: TOP => redmine:plugins:migrate => environment

**Comment by nanaksingh13** [comment]
I am facing similar issues

**Comment by whotopia** [comment]
This problem is coming from the redmine_maintenance_mode plugin and not this one.  This issue should really be closed.

**Comment by whotopia** [comment]
> Hello, some news? with this
> 
> ```
> Rails version 6.1.7
> Ruby version ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-linux-gnu]
> RubyGems version 3.3.5
> Rack version 2.2.4
> Middleware ActionDispatch::HostAuthorization, Rack::ContentLength, Rack::Sendfile, ActionDispatch::Static, ActionDispatch::Executor, ActiveSupport::Cache::Strategy::LocalCache::Middleware, Rack::Runtime, Rack::MethodOverride, ActionDispatch::RequestId, RequestStore::Middleware, ActionDispatch::RemoteIp, Rails::Rack::Logger, ActionDispatch::ShowExceptions, ActionDispatch::DebugExceptions, ActionDispatch::ActionableExceptions, ActionDispatch::Callbacks, ActionDispatch::Cookies, ActionDispatch::Session::CookieStore, ActionDispatch::Flash, ActionDispatch::ContentSecurityPolicy::Middleware, ActionDispatch::PermissionsPolicy::Middleware, Rack::Head, Rack::ConditionalGet, Rack::ETag, Rack::TempfileReaper
> Application root /opt/redmine-5.0.3
> Environment production
> Database adapter mysql2
> Database schema version 20220224194639
> ```
> 
> I got this error
> 
> ```
> ** Invoke redmine:plugins:migrate (first_time)
> ** Invoke environment (first_time)
> ** Execute environment
> rake aborted!
> LoadError: cannot load such file -- maintenance_mode_hooks
> /var/lib/gems/3.0.0/gems/zeitwerk-2.6.6/lib/zeitwerk/kernel.rb:38:in `require'
> /var/lib/gems/3.0.0/gems/zeitwerk-2.6.6/lib/zeitwerk/kernel.rb:38:in `require'
> /var/lib/gems/3.0.0/gems/activesupport-6.1.7/lib/active_support/dependencies/zeitwerk_integration.rb:51:in `require_dependency'
> /opt/redmine-5.0.3/plugins/redmine_maintenance_mode/init.rb:1:in `<top (required)>'
> /opt/redmine-5.0.3/lib/redmine/plugin_loader.rb:31:in `load'
> /opt/redmine-5.0.3/lib/redmine/plugin_loader.rb:31:in `run_initializer'
> /opt/redmine-5.0.3/lib/redmine/plugin_loader.rb:108:in `each'
> /opt/redmine-5.0.3/lib/redmine/plugin_loader.rb:108:in `block in load'
> /var/lib/gems/3.0.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:427:in `instance_exec'
> /var/lib/gems/3.0.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:427:in `block in make_lambda'
> /var/lib/gems/3.0.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'
> /var/lib/gems/3.0.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:604:in `block (2 levels) in default_terminator'
> /var/lib/gems/3.0.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:603:in `catch'
> /var/lib/gems/3.0.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:603:in `block in default_terminator'
> /var/lib/gems/3.0.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:199:in `block in halting'
> /var/lib/gems/3.0.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:512:in `block in invoke_before'
> /var/lib/gems/3.0.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:512:in `each'
> /var/lib/gems/3.0.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:512:in `invoke_before'
> /var/lib/gems/3.0.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:105:in `run_callbacks'
> /var/lib/gems/3.0.0/gems/activesupport-6.1.7/lib/active_support/reloader.rb:88:in `prepare!'
> /var/lib/gems/3.0.0/gems/railties-6.1.7/lib/rails/application/finisher.rb:124:in `block in <module:Finisher>'
> /var/lib/gems/3.0.0/gems/railties-6.1.7/lib/rails/initializable.rb:32:in `instance_exec'
> /var/lib/gems/3.0.0/gems/railties-6.1.7/lib/rails/initializable.rb:32:in `run'
> /var/lib/gems/3.0.0/gems/railties-6.1.7/lib/rails/initializable.rb:61:in `block in run_initializers'
> /usr/lib/ruby/3.0.0/tsort.rb:228:in `block in tsort_each'
> /usr/lib/ruby/3.0.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
> /usr/lib/ruby/3.0.0/tsort.rb:431:in `each_strongly_connected_component_from'
> /usr/lib/ruby/3.0.0/tsort.rb:349:in `block in each_strongly_connected_component'
> /usr/lib/ruby/3.0.0/tsort.rb:347:in `each'
> /usr/lib/ruby/3.0.0/tsort.rb:347:in `call'
> /usr/lib/ruby/3.0.0/tsort.rb:347:in `each_strongly_connected_component'
> /usr/lib/ruby/3.0.0/tsort.rb:226:in `tsort_each'
> /usr/lib/ruby/3.0.0/tsort.rb:205:in `tsort_each'
> /var/lib/gems/3.0.0/gems/railties-6.1.7/lib/rails/initializable.rb:60:in `run_initializers'
> /var/lib/gems/3.0.0/gems/railties-6.1.7/lib/rails/application.rb:391:in `initialize!'
> /opt/redmine-5.0.3/config/environment.rb:16:in `<top (required)>'
> /var/lib/gems/3.0.0/gems/zeitwerk-2.6.6/lib/zeitwerk/kernel.rb:38:in `require'
> /var/lib/gems/3.0.0/gems/zeitwerk-2.6.6/lib/zeitwerk/kernel.rb:38:in `require'
> /var/lib/gems/3.0.0/gems/activesupport-6.1.7/lib/active_support/dependencies.rb:332:in `block in require'
> /var/lib/gems/3.0.0/gems/activesupport-6.1.7/lib/active_support/dependencies.rb:299:in `load_dependency'
> /var/lib/gems/3.0.0/gems/activesupport-6.1.7/lib/active_support/dependencies.rb:332:in `require'
> /var/lib/gems/3.0.0/gems/railties-6.1.7/lib/rails/application.rb:367:in `require_environment!'
> /var/lib/gems/3.0.0/gems/railties-6.1.7/lib/rails/application.rb:533:in `block in run_tasks_blocks'
> /usr/share/rubygems-integration/all/gems/rake-13.0.6/lib/rake/task.rb:281:in `block in execute'
> /usr/share/rubygems-integration/all/gems/rake-13.0.6/lib/rake/task.rb:281:in `each'
> /usr/share/rubygems-integration/all/gems/rake-13.0.6/lib/rake/task.rb:281:in `execute'
> /usr/share/rubygems-integration/all/gems/rake-13.0.6/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
> /usr/share/rubygems-integration/all/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'
> /usr/share/rubygems-integration/all/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
> /usr/share/rubygems-integration/all/gems/rake-13.0.6/lib/rake/task.rb:243:in `block in invoke_prerequisites'
> /usr/share/rubygems-integration/all/gems/rake-13.0.6/lib/rake/task.rb:241:in `each'
> /usr/share/rubygems-integration/all/gems/rake-13.0.6/lib/rake/task.rb:241:in `invoke_prerequisites'
> /usr/share/rubygems-integration/all/gems/rake-13.0.6/lib/rake/task.rb:218:in `block in invoke_with_call_chain'
> /usr/share/rubygems-integration/all/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'
> /usr/share/rubygems-integration/all/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
> /usr/share/rubygems-integration/all/gems/rake-13.0.6/lib/rake/task.rb:188:in `invoke'
> /usr/share/rubygems-integration/all/gems/rake-13.0.6/lib/rake/application.rb:160:in `invoke_task'
> /usr/share/rubygems-integration/all/gems/rake-13.0.6/lib/rake/application.rb:116:in `block (2 levels) in top_level'
> /usr/share/rubygems-integration/all/gems/rake-13.0.6/lib/rake/application.rb:116:in `each'
> /usr/share/rubygems-integration/all/gems/rake-13.0.6/lib/rake/application.rb:116:in `block in top_level'
> /usr/share/rubygems-integration/all/gems/rake-13.0.6/lib/rake/application.rb:125:in `run_with_threads'
> /usr/share/rubygems-integration/all/gems/rake-13.0.6/lib/rake/application.rb:110:in `top_level'
> /usr/share/rubygems-integration/all/gems/rake-13.0.6/lib/rake/application.rb:83:in `block in run'
> /usr/share/rubygems-integration/all/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
> /usr/share/rubygems-integration/all/gems/rake-13.0.6/lib/rake/application.rb:80:in `run'
> /usr/share/rubygems-integration/all/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
> /usr/bin/rake:25:in `load'
> /usr/bin/rake:25:in `<main>'
> Tasks: TOP => redmine:plugins:migrate => environment
> ```


This problem is coming from the redmine_maintenance_mode plugin and not this one.
