### ISSUE TITLE
On 5.1.2 rake redmine:plugins fails (plugin still useable by others)

### ISSUE THREAD

**Issue by aseques** [jbbarth/redmine_base_deface#17]
I installed redmine_base_deface as a requirement for redmine_better_overview, the setup has two parts the bundle install that works without issues (adding deface and other gems)

And then the *rake redmine:plugins* that fails with an error (similar to others in the issues)

> 
> # rake redmine:plugins
> rake aborted!
> LoadError: cannot load such file -- listen
> /var/lib/gems/3.0.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
> /var/lib/gems/3.0.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
> /var/lib/gems/3.0.0/gems/zeitwerk-2.6.16/lib/zeitwerk/kernel.rb:34:in `require'
> /var/lib/gems/3.0.0/gems/activesupport-6.1.7.8/lib/active_support/dependencies.rb:332:in `block in require'
> /var/lib/gems/3.0.0/gems/activesupport-6.1.7.8/lib/active_support/dependencies.rb:299:in `load_dependency'
> /var/lib/gems/3.0.0/gems/activesupport-6.1.7.8/lib/active_support/dependencies.rb:332:in `require'
> /var/lib/gems/3.0.0/gems/activesupport-6.1.7.8/lib/active_support/evented_file_update_checker.rb:6:in `<top (required)>'
> /var/lib/gems/3.0.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
> /var/lib/gems/3.0.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
> /var/lib/gems/3.0.0/gems/zeitwerk-2.6.16/lib/zeitwerk/kernel.rb:34:in `require'
> /var/lib/gems/3.0.0/gems/activesupport-6.1.7.8/lib/active_support/dependencies.rb:332:in `block in require'
> /var/lib/gems/3.0.0/gems/activesupport-6.1.7.8/lib/active_support/dependencies.rb:299:in `load_dependency'
> /var/lib/gems/3.0.0/gems/activesupport-6.1.7.8/lib/active_support/dependencies.rb:332:in `require'
> /var/www/redmine/config/environments/development.rb:58:in `block in <top (required)>'
> /var/lib/gems/3.0.0/gems/railties-6.1.7.8/lib/rails/railtie.rb:234:in `instance_eval'
> /var/lib/gems/3.0.0/gems/railties-6.1.7.8/lib/rails/railtie.rb:234:in `configure'
> /var/www/redmine/config/environments/development.rb:5:in `<top (required)>'
> /var/lib/gems/3.0.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
> /var/lib/gems/3.0.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
> /var/lib/gems/3.0.0/gems/zeitwerk-2.6.16/lib/zeitwerk/kernel.rb:34:in `require'
> /var/lib/gems/3.0.0/gems/activesupport-6.1.7.8/lib/active_support/dependencies.rb:332:in `block in require'
> /var/lib/gems/3.0.0/gems/activesupport-6.1.7.8/lib/active_support/dependencies.rb:299:in `load_dependency'
> /var/lib/gems/3.0.0/gems/activesupport-6.1.7.8/lib/active_support/dependencies.rb:332:in `require'
> /var/lib/gems/3.0.0/gems/railties-6.1.7.8/lib/rails/engine.rb:571:in `block (2 levels) in <class:Engine>'
> /var/lib/gems/3.0.0/gems/railties-6.1.7.8/lib/rails/engine.rb:570:in `each'
> /var/lib/gems/3.0.0/gems/railties-6.1.7.8/lib/rails/engine.rb:570:in `block in <class:Engine>'
> /var/lib/gems/3.0.0/gems/railties-6.1.7.8/lib/rails/initializable.rb:32:in `instance_exec'
> /var/lib/gems/3.0.0/gems/railties-6.1.7.8/lib/rails/initializable.rb:32:in `run'
> /var/lib/gems/3.0.0/gems/railties-6.1.7.8/lib/rails/initializable.rb:61:in `block in run_initializers'
> /var/lib/gems/3.0.0/gems/railties-6.1.7.8/lib/rails/initializable.rb:50:in `each'
> /var/lib/gems/3.0.0/gems/railties-6.1.7.8/lib/rails/initializable.rb:50:in `tsort_each_child'
> /var/lib/gems/3.0.0/gems/railties-6.1.7.8/lib/rails/initializable.rb:60:in `run_initializers'
> /var/lib/gems/3.0.0/gems/railties-6.1.7.8/lib/rails/application.rb:391:in `initialize!'
> /var/www/redmine/config/environment.rb:16:in `<top (required)>'
> /var/lib/gems/3.0.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
> /var/lib/gems/3.0.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
> /var/lib/gems/3.0.0/gems/zeitwerk-2.6.16/lib/zeitwerk/kernel.rb:34:in `require'
> /var/lib/gems/3.0.0/gems/activesupport-6.1.7.8/lib/active_support/dependencies.rb:332:in `block in require'
> /var/lib/gems/3.0.0/gems/activesupport-6.1.7.8/lib/active_support/dependencies.rb:299:in `load_dependency'
> /var/lib/gems/3.0.0/gems/activesupport-6.1.7.8/lib/active_support/dependencies.rb:332:in `require'
> /var/lib/gems/3.0.0/gems/railties-6.1.7.8/lib/rails/application.rb:367:in `require_environment!'
> /var/lib/gems/3.0.0/gems/railties-6.1.7.8/lib/rails/application.rb:533:in `block in run_tasks_blocks'
> /var/www/redmine/lib/tasks/redmine.rake:73:in `block (2 levels) in <top (required)>'
> /var/lib/gems/3.0.0/gems/rake-13.2.1/exe/rake:27:in `<top (required)>'
> Tasks: TOP => redmine:plugins:migrate => environment
> (See full trace by running task with --trace)
> 

It seems that redmine_better_overview doesn't need the second part so it works for me but still something is not properly installed.

**Comment by aseques** [comment]
Hi @nanego  the redmine_better_overview works fine (it probably needs only some parts of the redmine_base_deface plugin), the error is on the last setup part for redmine_base_deface (that so far hasn't been required for any other of the plugins I have installed)

**Comment by maxrossello** [comment]
Hi @aseques , would you mind trying my fork at https://github.com/maxrossello/redmine_base_deface ?
If it turns to be beneficial, I will be glad to create a pull request.
Here are the differences
![immagine](https://github.com/jbbarth/redmine_base_deface/assets/4066651/b41341f7-bac8-417e-8441-151bb1ac8447)

**Comment by aseques** [comment]
Hi @maxrossello I've just tried still fails with a similar error, see also attached the versions I'm using if it's useful to diagnose the issue

Environment:
  Redmine version                5.1.3.stable
  Ruby version                   3.0.2-p107 (2021-07-07) [x86_64-linux-gnu]
  Rails version                  6.1.7.8
  Environment                    production
  Database adapter               PostgreSQL
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp

```

$ rake redmine:plugins
(in /var/www/redmine)
rake aborted!
LoadError: cannot load such file -- listen
/var/lib/gems/3.0.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/var/lib/gems/3.0.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/var/lib/gems/3.0.0/gems/zeitwerk-2.6.16/lib/zeitwerk/kernel.rb:34:in `require'
/var/lib/gems/3.0.0/gems/activesupport-6.1.7.8/lib/active_support/dependencies.rb:332:in `block in require'
/var/lib/gems/3.0.0/gems/activesupport-6.1.7.8/lib/active_support/dependencies.rb:299:in `load_dependency'
/var/lib/gems/3.0.0/gems/activesupport-6.1.7.8/lib/active_support/dependencies.rb:332:in `require'
/var/lib/gems/3.0.0/gems/activesupport-6.1.7.8/lib/active_support/evented_file_update_checker.rb:6:in `<top (required)>'
/var/lib/gems/3.0.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/var/lib/gems/3.0.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/var/lib/gems/3.0.0/gems/zeitwerk-2.6.16/lib/zeitwerk/kernel.rb:34:in `require'
/var/lib/gems/3.0.0/gems/activesupport-6.1.7.8/lib/active_support/dependencies.rb:332:in `block in require'
/var/lib/gems/3.0.0/gems/activesupport-6.1.7.8/lib/active_support/dependencies.rb:299:in `load_dependency'
/var/lib/gems/3.0.0/gems/activesupport-6.1.7.8/lib/active_support/dependencies.rb:332:in `require'
/var/www/redmine/config/environments/development.rb:58:in `block in <top (required)>'
/var/lib/gems/3.0.0/gems/railties-6.1.7.8/lib/rails/railtie.rb:234:in `instance_eval'
/var/lib/gems/3.0.0/gems/railties-6.1.7.8/lib/rails/railtie.rb:234:in `configure'
/var/www/redmine/config/environments/development.rb:5:in `<top (required)>'
/var/lib/gems/3.0.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/var/lib/gems/3.0.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/var/lib/gems/3.0.0/gems/zeitwerk-2.6.16/lib/zeitwerk/kernel.rb:34:in `require'
/var/lib/gems/3.0.0/gems/activesupport-6.1.7.8/lib/active_support/dependencies.rb:332:in `block in require'
/var/lib/gems/3.0.0/gems/activesupport-6.1.7.8/lib/active_support/dependencies.rb:299:in `load_dependency'
/var/lib/gems/3.0.0/gems/activesupport-6.1.7.8/lib/active_support/dependencies.rb:332:in `require'
/var/lib/gems/3.0.0/gems/railties-6.1.7.8/lib/rails/engine.rb:571:in `block (2 levels) in <class:Engine>'
/var/lib/gems/3.0.0/gems/railties-6.1.7.8/lib/rails/engine.rb:570:in `each'
/var/lib/gems/3.0.0/gems/railties-6.1.7.8/lib/rails/engine.rb:570:in `block in <class:Engine>'
/var/lib/gems/3.0.0/gems/railties-6.1.7.8/lib/rails/initializable.rb:32:in `instance_exec'
/var/lib/gems/3.0.0/gems/railties-6.1.7.8/lib/rails/initializable.rb:32:in `run'
/var/lib/gems/3.0.0/gems/railties-6.1.7.8/lib/rails/initializable.rb:61:in `block in run_initializers'
/var/lib/gems/3.0.0/gems/railties-6.1.7.8/lib/rails/initializable.rb:50:in `each'
/var/lib/gems/3.0.0/gems/railties-6.1.7.8/lib/rails/initializable.rb:50:in `tsort_each_child'
/var/lib/gems/3.0.0/gems/railties-6.1.7.8/lib/rails/initializable.rb:60:in `run_initializers'
/var/lib/gems/3.0.0/gems/railties-6.1.7.8/lib/rails/application.rb:391:in `initialize!'
/var/www/redmine/config/environment.rb:16:in `<top (required)>'
/var/lib/gems/3.0.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/var/lib/gems/3.0.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/var/lib/gems/3.0.0/gems/zeitwerk-2.6.16/lib/zeitwerk/kernel.rb:34:in `require'
/var/lib/gems/3.0.0/gems/activesupport-6.1.7.8/lib/active_support/dependencies.rb:332:in `block in require'
/var/lib/gems/3.0.0/gems/activesupport-6.1.7.8/lib/active_support/dependencies.rb:299:in `load_dependency'
/var/lib/gems/3.0.0/gems/activesupport-6.1.7.8/lib/active_support/dependencies.rb:332:in `require'
/var/lib/gems/3.0.0/gems/railties-6.1.7.8/lib/rails/application.rb:367:in `require_environment!'
/var/lib/gems/3.0.0/gems/railties-6.1.7.8/lib/rails/application.rb:533:in `block in run_tasks_blocks'
/var/www/redmine/lib/tasks/redmine.rake:73:in `block (2 levels) in <top (required)>'
/var/lib/gems/3.0.0/gems/rake-13.2.1/exe/rake:27:in `<top (required)>'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)
```

**Comment by nanego** [comment]
Did you install all the required gems ? with "bundle update" ?

**Comment by maxrossello** [comment]
@aseques rake still works for me, but anyways get used to use `bundle exec rails` instead.

So try to run `bundle exec rails redmine:plugins` which won't go through the rake gem

**Comment by aseques** [comment]
@nanego  I don't have the listen gem installed (It doesn't show on any of the Gemfiles as a dependency)

@maxrossello I still get some of the errors with the last command you showed

```

# bundle exec rails redmine:plugins --trace
** Invoke redmine:plugins (first_time)
** Execute redmine:plugins
** Invoke redmine:plugins:migrate (first_time)
** Invoke environment (first_time)
** Execute environment
rails aborted!
LoadError: cannot load such file -- listen
/var/lib/gems/3.0.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/var/lib/gems/3.0.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/var/lib/gems/3.0.0/gems/zeitwerk-2.6.16/lib/zeitwerk/kernel.rb:34:in `require'
/var/lib/gems/3.0.0/gems/activesupport-6.1.7.8/lib/active_support/dependencies.rb:332:in `block in require'
/var/lib/gems/3.0.0/gems/activesupport-6.1.7.8/lib/active_support/dependencies.rb:299:in `load_dependency'
/var/lib/gems/3.0.0/gems/activesupport-6.1.7.8/lib/active_support/dependencies.rb:332:in `require'
/var/lib/gems/3.0.0/gems/activesupport-6.1.7.8/lib/active_support/evented_file_update_checker.rb:6:in `<top (required)>'
/var/lib/gems/3.0.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/var/lib/gems/3.0.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/var/lib/gems/3.0.0/gems/zeitwerk-2.6.16/lib/zeitwerk/kernel.rb:34:in `require'
/var/lib/gems/3.0.0/gems/activesupport-6.1.7.8/lib/active_support/dependencies.rb:332:in `block in require'
/var/lib/gems/3.0.0/gems/activesupport-6.1.7.8/lib/active_support/dependencies.rb:299:in `load_dependency'
/var/lib/gems/3.0.0/gems/activesupport-6.1.7.8/lib/active_support/dependencies.rb:332:in `require'
/var/www/redmine/config/environments/development.rb:58:in `block in <top (required)>'
/var/lib/gems/3.0.0/gems/railties-6.1.7.8/lib/rails/railtie.rb:234:in `instance_eval'
/var/lib/gems/3.0.0/gems/railties-6.1.7.8/lib/rails/railtie.rb:234:in `configure'
/var/www/redmine/config/environments/development.rb:5:in `<top (required)>'
/var/lib/gems/3.0.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/var/lib/gems/3.0.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/var/lib/gems/3.0.0/gems/zeitwerk-2.6.16/lib/zeitwerk/kernel.rb:34:in `require'
/var/lib/gems/3.0.0/gems/activesupport-6.1.7.8/lib/active_support/dependencies.rb:332:in `block in require'
/var/lib/gems/3.0.0/gems/activesupport-6.1.7.8/lib/active_support/dependencies.rb:299:in `load_dependency'
/var/lib/gems/3.0.0/gems/activesupport-6.1.7.8/lib/active_support/dependencies.rb:332:in `require'
/var/lib/gems/3.0.0/gems/railties-6.1.7.8/lib/rails/engine.rb:571:in `block (2 levels) in <class:Engine>'
/var/lib/gems/3.0.0/gems/railties-6.1.7.8/lib/rails/engine.rb:570:in `each'
/var/lib/gems/3.0.0/gems/railties-6.1.7.8/lib/rails/engine.rb:570:in `block in <class:Engine>'
/var/lib/gems/3.0.0/gems/railties-6.1.7.8/lib/rails/initializable.rb:32:in `instance_exec'
/var/lib/gems/3.0.0/gems/railties-6.1.7.8/lib/rails/initializable.rb:32:in `run'
/var/lib/gems/3.0.0/gems/railties-6.1.7.8/lib/rails/initializable.rb:61:in `block in run_initializers'
/usr/lib/ruby/3.0.0/tsort.rb:228:in `block in tsort_each'
/usr/lib/ruby/3.0.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
/usr/lib/ruby/3.0.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
/usr/lib/ruby/3.0.0/tsort.rb:431:in `each_strongly_connected_component_from'
/usr/lib/ruby/3.0.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
/var/lib/gems/3.0.0/gems/railties-6.1.7.8/lib/rails/initializable.rb:50:in `each'
/var/lib/gems/3.0.0/gems/railties-6.1.7.8/lib/rails/initializable.rb:50:in `tsort_each_child'
/usr/lib/ruby/3.0.0/tsort.rb:415:in `call'
/usr/lib/ruby/3.0.0/tsort.rb:415:in `each_strongly_connected_component_from'
/usr/lib/ruby/3.0.0/tsort.rb:349:in `block in each_strongly_connected_component'
/usr/lib/ruby/3.0.0/tsort.rb:347:in `each'
/usr/lib/ruby/3.0.0/tsort.rb:347:in `call'
/usr/lib/ruby/3.0.0/tsort.rb:347:in `each_strongly_connected_component'
/usr/lib/ruby/3.0.0/tsort.rb:226:in `tsort_each'
/usr/lib/ruby/3.0.0/tsort.rb:205:in `tsort_each'
/var/lib/gems/3.0.0/gems/railties-6.1.7.8/lib/rails/initializable.rb:60:in `run_initializers'
/var/lib/gems/3.0.0/gems/railties-6.1.7.8/lib/rails/application.rb:391:in `initialize!'
/var/www/redmine/config/environment.rb:16:in `<top (required)>'
/var/lib/gems/3.0.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/var/lib/gems/3.0.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/var/lib/gems/3.0.0/gems/zeitwerk-2.6.16/lib/zeitwerk/kernel.rb:34:in `require'
/var/lib/gems/3.0.0/gems/activesupport-6.1.7.8/lib/active_support/dependencies.rb:332:in `block in require'
/var/lib/gems/3.0.0/gems/activesupport-6.1.7.8/lib/active_support/dependencies.rb:299:in `load_dependency'
/var/lib/gems/3.0.0/gems/activesupport-6.1.7.8/lib/active_support/dependencies.rb:332:in `require'
/var/lib/gems/3.0.0/gems/railties-6.1.7.8/lib/rails/application.rb:367:in `require_environment!'
/var/lib/gems/3.0.0/gems/railties-6.1.7.8/lib/rails/application.rb:533:in `block in run_tasks_blocks'
/var/lib/gems/3.0.0/gems/rake-13.2.1/lib/rake/task.rb:281:in `block in execute'
/var/lib/gems/3.0.0/gems/rake-13.2.1/lib/rake/task.rb:281:in `each'
/var/lib/gems/3.0.0/gems/rake-13.2.1/lib/rake/task.rb:281:in `execute'
/var/lib/gems/3.0.0/gems/rake-13.2.1/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/var/lib/gems/3.0.0/gems/rake-13.2.1/lib/rake/task.rb:199:in `synchronize'
/var/lib/gems/3.0.0/gems/rake-13.2.1/lib/rake/task.rb:199:in `invoke_with_call_chain'
/var/lib/gems/3.0.0/gems/rake-13.2.1/lib/rake/task.rb:243:in `block in invoke_prerequisites'
/var/lib/gems/3.0.0/gems/rake-13.2.1/lib/rake/task.rb:241:in `each'
/var/lib/gems/3.0.0/gems/rake-13.2.1/lib/rake/task.rb:241:in `invoke_prerequisites'
/var/lib/gems/3.0.0/gems/rake-13.2.1/lib/rake/task.rb:218:in `block in invoke_with_call_chain'
/var/lib/gems/3.0.0/gems/rake-13.2.1/lib/rake/task.rb:199:in `synchronize'
/var/lib/gems/3.0.0/gems/rake-13.2.1/lib/rake/task.rb:199:in `invoke_with_call_chain'
/var/lib/gems/3.0.0/gems/rake-13.2.1/lib/rake/task.rb:188:in `invoke'
/var/www/redmine/lib/tasks/redmine.rake:73:in `block (2 levels) in <top (required)>'
/var/lib/gems/3.0.0/gems/rake-13.2.1/lib/rake/task.rb:281:in `block in execute'
/var/lib/gems/3.0.0/gems/rake-13.2.1/lib/rake/task.rb:281:in `each'
/var/lib/gems/3.0.0/gems/rake-13.2.1/lib/rake/task.rb:281:in `execute'
/var/lib/gems/3.0.0/gems/rake-13.2.1/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/var/lib/gems/3.0.0/gems/rake-13.2.1/lib/rake/task.rb:199:in `synchronize'
/var/lib/gems/3.0.0/gems/rake-13.2.1/lib/rake/task.rb:199:in `invoke_with_call_chain'
/var/lib/gems/3.0.0/gems/rake-13.2.1/lib/rake/task.rb:188:in `invoke'
/var/lib/gems/3.0.0/gems/rake-13.2.1/lib/rake/application.rb:188:in `invoke_task'
/var/lib/gems/3.0.0/gems/rake-13.2.1/lib/rake/application.rb:138:in `block (2 levels) in top_level'
/var/lib/gems/3.0.0/gems/rake-13.2.1/lib/rake/application.rb:138:in `each'
/var/lib/gems/3.0.0/gems/rake-13.2.1/lib/rake/application.rb:138:in `block in top_level'
/var/lib/gems/3.0.0/gems/rake-13.2.1/lib/rake/application.rb:147:in `run_with_threads'
/var/lib/gems/3.0.0/gems/rake-13.2.1/lib/rake/application.rb:132:in `top_level'
/var/lib/gems/3.0.0/gems/railties-6.1.7.8/lib/rails/commands/rake/rake_command.rb:24:in `block (2 levels) in perform'
/var/lib/gems/3.0.0/gems/rake-13.2.1/lib/rake/application.rb:214:in `standard_exception_handling'
/var/lib/gems/3.0.0/gems/railties-6.1.7.8/lib/rails/commands/rake/rake_command.rb:24:in `block in perform'
/var/lib/gems/3.0.0/gems/rake-13.2.1/lib/rake/rake_module.rb:59:in `with_application'
/var/lib/gems/3.0.0/gems/railties-6.1.7.8/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/var/lib/gems/3.0.0/gems/railties-6.1.7.8/lib/rails/command.rb:50:in `invoke'
/var/lib/gems/3.0.0/gems/railties-6.1.7.8/lib/rails/commands.rb:18:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => redmine:plugins:migrate => environment

```

**Comment by maxrossello** [comment]
Can you post your config/environments/development.rb please?

**Comment by aseques** [comment]
hi @maxrossello here you go 
```

# frozen_string_literal: true

require 'active_support/core_ext/integer/time'

Rails.application.configure do
  # Settings specified here will take precedence over those in config/application.rb.

  # In the development environment your application's code is reloaded any time
  # it changes. This slows down response time but is perfect for development
  # since you don't have to restart the web server when you make code changes.
  config.cache_classes = false

  # Do not eager load code on boot.
  config.eager_load = false

  # Show full error reports.
  config.consider_all_requests_local = true

  # Enable/disable caching. By default caching is disabled.
  # Run rails dev:cache to toggle caching.
  if Rails.root.join('tmp', 'caching-dev.txt').exist?
    config.action_controller.perform_caching = true
    config.action_controller.enable_fragment_cache_logging = true

    config.cache_store = :memory_store
    config.public_file_server.headers = {
      'Cache-Control' => "public, max-age=#{2.days.to_i}"
    }
  else
    config.action_controller.perform_caching = false

    config.cache_store = :null_store
  end

  # Print deprecation notices to the Rails logger.
  config.active_support.deprecation = [:stderr, :log]

  # Raise exceptions for disallowed deprecations.
  config.active_support.disallowed_deprecation = :raise

  # Tell Active Support which deprecation messages to disallow.
  config.active_support.disallowed_deprecation_warnings = []

  # Raise an error on page load if there are pending migrations.
  config.active_record.migration_error = :page_load

  # Highlight code that triggered database queries in logs.
  config.active_record.verbose_query_logs = true

  # Raises error for missing translations.
  # config.i18n.raise_on_missing_translations = true

  # Annotate rendered view with file names.
  config.action_view.annotate_rendered_view_with_filenames = true

  # Use an evented file watcher to asynchronously detect changes in source code,
  # routes, locales, etc. This feature depends on the listen gem.
  config.file_watcher = ActiveSupport::EventedFileUpdateChecker

  # Uncomment if you wish to allow Action Cable access from any origin.
  # config.action_cable.disable_request_forgery_protection = true
end

```

**Comment by maxrossello** [comment]
This problem does not seem related to any plugin. First answer by @nanego is relevant. In Gemfile, you should find the following at line 91:

group :development do
  gem 'listen', '~> 3.3'
  gem "yard"
end

so by running 'RAILS_ENV=development bundle install' or 'RAILS_ENV=development bundle update' you should be all set. Alternatively, you may install the listen gem manually

**Comment by aseques** [comment]
Sorry for being so late to reply, while checking on my install notes, I found that I installed everything passing the production variable and the end. I just rechecked with 
> bundle exec rake redmine:plugins RAILS_ENV=production
Now it didn't throw any errors, so the problem was probably in the command I passed.

Regards.
