### ISSUE TITLE
incompatibility with additionnals plugin

### ISSUE THREAD

**Issue by undigo** [jbbarth/redmine_base_deface#7]
Try to migrate your plugin :
but error on log trace here
bash-4.2# rake redmine:plugins:migrate RAILS_ENV=production --trace
** Invoke redmine:plugins:migrate (first_time)
** Invoke environment (first_time)
** Execute environment
rake aborted!

additionals plugin cannot be used with redmine_base_deface plugin'.
/opt/bitnami/apps/redmine/htdocs/plugins/additionals/lib/additionals.rb:74:in `block in incompatible_plugins'
/opt/bitnami/apps/redmine/htdocs/plugins/additionals/lib/additionals.rb:73:in `each'
/opt/bitnami/apps/redmine/htdocs/plugins/additionals/lib/additionals.rb:73:in `incompatible_plugins'
/opt/bitnami/apps/redmine/htdocs/plugins/additionals/lib/additionals.rb:7:in `setup'
/opt/bitnami/apps/redmine/htdocs/plugins/additionals/init.rb:43:in `block in <top (required)>'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:446:in `instance_exec'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:446:in `block in make_lambda'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:192:in `block in simple'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:504:in `block in call'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:504:in `each'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:504:in `call'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:778:in `_run_prepare_callbacks'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:81:in `run_callbacks'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/reloader.rb:83:in `prepare!'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/reloader.rb:55:in `prepare!'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/railties-4.2.8/lib/rails/application/finisher.rb:50:in `block in <module:Finisher>'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/railties-4.2.8/lib/rails/initializable.rb:30:in `instance_exec'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/railties-4.2.8/lib/rails/initializable.rb:30:in `run'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/railties-4.2.8/lib/rails/initializable.rb:55:in `block in run_initializers'
/opt/bitnami/ruby/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
/opt/bitnami/ruby/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
/opt/bitnami/ruby/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
/opt/bitnami/ruby/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
/opt/bitnami/ruby/lib/ruby/2.3.0/tsort.rb:347:in `each'
/opt/bitnami/ruby/lib/ruby/2.3.0/tsort.rb:347:in `call'
/opt/bitnami/ruby/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
/opt/bitnami/ruby/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
/opt/bitnami/ruby/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/railties-4.2.8/lib/rails/initializable.rb:54:in `run_initializers'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/railties-4.2.8/lib/rails/application.rb:352:in `initialize!'
/opt/bitnami/apps/redmine/htdocs/config/environment.rb:14:in `<top (required)>'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/railties-4.2.8/lib/rails/application.rb:328:in `require_environment!'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/railties-4.2.8/lib/rails/application.rb:457:in `block in run_tasks_blocks'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/rake-12.2.1/lib/rake/task.rb:251:in `block in execute'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/rake-12.2.1/lib/rake/task.rb:251:in `each'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/rake-12.2.1/lib/rake/task.rb:251:in `execute'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/rake-12.2.1/lib/rake/task.rb:195:in `block in invoke_with_call_chain'
/opt/bitnami/ruby/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/rake-12.2.1/lib/rake/task.rb:188:in `invoke_with_call_chain'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/rake-12.2.1/lib/rake/task.rb:217:in `block in invoke_prerequisites'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/rake-12.2.1/lib/rake/task.rb:215:in `each'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/rake-12.2.1/lib/rake/task.rb:215:in `invoke_prerequisites'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/rake-12.2.1/lib/rake/task.rb:194:in `block in invoke_with_call_chain'
/opt/bitnami/ruby/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/rake-12.2.1/lib/rake/task.rb:188:in `invoke_with_call_chain'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/rake-12.2.1/lib/rake/task.rb:181:in `invoke'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/rake-12.2.1/lib/rake/application.rb:160:in `invoke_task'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/rake-12.2.1/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/rake-12.2.1/lib/rake/application.rb:116:in `each'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/rake-12.2.1/lib/rake/application.rb:116:in `block in top_level'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/rake-12.2.1/lib/rake/application.rb:125:in `run_with_threads'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/rake-12.2.1/lib/rake/application.rb:110:in `top_level'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/rake-12.2.1/lib/rake/application.rb:83:in `block in run'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/rake-12.2.1/lib/rake/application.rb:186:in `standard_exception_handling'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/rake-12.2.1/lib/rake/application.rb:80:in `run'
/opt/bitnami/ruby/lib/ruby/gems/2.3.0/gems/rake-12.2.1/exe/rake:27:in `<top (required)>'
/opt/bitnami/ruby/bin/rake:23:in `load'
/opt/bitnami/ruby/bin/rake:23:in `<main>'
Tasks: TOP => redmine:plugins:migrate => environment
bash-4.2# exit
exit

config Redmine :Environment:
  Redmine version                3.4.3.stable
  Ruby version                   2.3.5-p376 (2017-09-14) [x86_64-linux]
  Rails version                  4.2.8
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.9.7
  Git                            2.14.1
  Filesystem                     
Redmine plugins:
  additionals                    2.0.11
  clipboard_image_paste          1.12
  computed_custom_field          1.0.6
  disable_activity               0.0.1
  event_notifications            2.4.1
  redmine_banner                 0.1.2
  redmine_ckeditor               1.1.5
  redmine_custom_css             0.1.7
  redmine_custom_reports         0.1.5
  redmine_default_custom_query   1.3.0
  redmine_drafts                 0.2.0
  redmine_email_notification_content_filter 0.0.2
  redmine_issue_templates        0.1.8
  redmine_knowledgebase          3.3.1
  redmine_landing_page           0.1.1
  redmine_logs                   0.1.1
  redmine_privacy_terms          1.0.0
  redmine_tkgmap                 0.1
  redmine_workflow_enhancements  0.5.0

a error from your plugin or with additionals plugins ?
The goal is to use redmine_datetime_custom_field plugin

Regards,

**Comment by alexandermeindl** [comment]
One solution for it would be, to remove this line in redmine_datetime_custom_field https://github.com/nanego/redmine_datetime_custom_field/blob/master/init.rb#L11. _additionals_ provides deface like _redmine_base_deface_. This means, if you use _additionals_, you do not require _redmine_base_deface_ anymore.

**Comment by andreav** [comment]
Same problem here.
I changed additionals  plugin Gemfile from '1.3.2' to '1.5.3'

Installation succeded, for the moment it seems to work.

**Comment by alexandermeindl** [comment]
> Same problem here.
> I changed additionals plugin Gemfile from '1.3.2' to '1.5.3'
> 
> Installation succeded, for the moment it seems to work.

Hi @andreav,
in the upcoming stable additionals plugin there is 1.5.3 used, which is compatible with redmine_base_deface again. Your change shouldn't be a problem with additionals plugin.
